name: Cloudflare VDS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          sudo apt update
          sudo apt install -y openssh-server curl
          
          echo "root:123123123haN@@" | sudo chpasswd
          
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          
          sudo service ssh restart

      - name: Install Cloudflared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Start Tunnel
        run: cloudflared tunnel --url tcp://localhost:22
