name: Cloudflare VDS Persistent Fake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo clone
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          sudo apt update
          sudo apt install -y openssh-server curl git
          
          echo "root:123123123haN@@" | sudo chpasswd
          
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          
          sudo service ssh restart

      - name: Install Cloudflare
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Start Tunnel (SHOW LINK)
        run: |
          cloudflared tunnel --url tcp://localhost:22 | tee tunnel.log &

          sleep 10
          echo "====== TUNNEL INFO ======"
          cat tunnel.log

      - name: Keep Alive
        run: sleep 21600

      - name: Save Files
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@example.com"
          git add .
          git commit -m "auto save" || echo "no changes"
          git push
